### ISSUE TITLE
List of possible missing stuff

### ISSUE THREAD

**Issue by jriwanek** [EXTER7/BaseMaterials#2]
Wood Rod
Stone Rod
Obsidian Rod
Block of Charcoal (Likely outside of mod scope, but you don't ask, you don't get)

Aluminum
Titanium (Some people prefer this to be a native ore, others by blending it from Rutile and Magnesium)
Rutile
Magnesium

Wood Gear
Obsidian Gear/Plate
Maybe Diamond + Emerald Gears? (Possibly Plates and the like too)
Diamond Dust/Liquid Diamond
Emerald Dust/Liquid Emerald

Emerald/Diamond/Enderpearl Shards. (Some mods prefer to refer to them as ingots)

**Comment by 0Navis0** [comment]
I come to add some missing content with the Chrome, Mercure and Iridium, Calcium, Silicium and Phosphore.

**Comment by ruyanve** [comment]
Osmium Ore from Mekanism would be a great addition as well! The 1.9.4 will be released next week...
https://github.com/aidancbrady/Mekanism
http://wiki.aidancbrady.com/wiki/Osmium_Ore

**Comment by jriwanek** [comment]
Due to lack of response from the author, I ended up working with Cyanobacterium on basemetals, also made modernmetals, you can find almost all of the above between those and 'Cyano's *Advantage mods.
