### ISSUE TITLE
[1.9.4][Suggestion] Add Aluminium

### ISSUE THREAD

**Issue by Xiaminou** [EXTER7/BaseMaterials#7]
I need aluminium for a few different recipes in my modpack, but I've yet to find a mod that adds aluminium. Any chance you could take care of it?

**Comment by jriwanek** [comment]
If he doesn't you could always check out modernmetals, http://minecraft.curseforge.com/projects/modern-metals I'll be releasing it for 1.9.4 soon.

**Comment by EXTER7** [comment]
Aluminium and chromium are going to be added in the next release.

**Comment by Xiaminou** [comment]
Thanks, I'm having a look at it and I see you've named it Aluminium (probably my fault), which is fine however for the Ore Dictionary I do believe people use "Aluminum", you might want to register both entries, for compatibility.
https://en.wikipedia.org/wiki/Aluminium

**Comment by EXTER7** [comment]
Version 1.4.0.1 now registers aluminium items as "Aluminum" in the Ore Dictionary.
